name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '20'  # Update to Node.js version 20

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag my-react-app:${{ github.sha }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          node-version: '20'  # Add Node.js version 20 here

      - name: Push Docker image to Docker Hub
        run: docker push my-react-app:${{ github.sha }}
